name: Buf Push

on:
  push:
    branches: [ main ]
    paths:
      - '**.proto'
      - '**/buf.yaml'
      - '**/buf.lock'
      - '**/buf.md'
      - '**/README.md'
      - '**/LICENSE'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Buf
        uses: bufbuild/buf-action@v1
        with:
          version: "1.28.1"
          token: ${{ secrets.BUF_TOKEN }}
          input: "."
          format: true
          lint: true
          breaking: true
          push: true
          push_create_visibility: "public"
